version: 0.2
phases:
  pre_build:
    commands:
      #dockerlogin
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
  build:
    commands:
      - docker build -t sample-task3-myangularapp546:latest .
  post_build:
    commands:
      - docker tag sample-task3-myangularapp546:latest ${DOCKERHUB_USER}/sample-task3-myangularapp546:latest
      - docker push ${DOCKERHUB_USER}/sample-task3-myangularapp546:latest
