version: 0.2

env:
  variables:
    ECR_REPO_NAME: sample-task3-myangularapp546

phases:                     # ← moved out to top level
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} \
          | docker login --username AWS --password-stdin ${ECR_MAIN_URI}
      - IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"

  build:
    commands:
      - docker build -t ${ECR_REPO_NAME}:latest .

  post_build:
    commands:
      - docker tag ${ECR_REPO_NAME}:latest ${IMAGE_URI}
      - docker push ${IMAGE_URI}

artifacts:
  # you can leave this empty or remove it if you don't need CodeBuild to upload
  # any files back to the pipeline. Docker images go to ECR, not here.
  files:
    - '**/*'
